### ISSUE TITLE
Cannot achieve the various metrics described in the paper after running the code.

### ISSUE THREAD

**Issue by PengPeixi** [SuperSupermoon/MedViLL#6]
Hello, your code cannot achieve the various metrics described in the paper after running. Could you please provide the hyperparameters you set before running, and the training log after running.

**Comment by SuperSupermoon** [comment]
Hello, PengPeixi. Thank you for your interest. We will provide hyperparameters and training logs soon. In the meantime, for which tasks in the paper were you unable to achieve metrics? We would appreciate it if you could leave a specific issue.

**Comment by PengPeixi** [comment]
For example, for the downstream task of medical report generation, after running the file generation_decode.py on the openi dataset, the metrics obtained by the MedViLL model are: 
{'bleu 1': 0.15519337010503506, 'bleu 2': 0.09391290091144913, 'bleu 3': 0.05791537394797654, 'bleu 4': 0.03430614826591653, 'best_bleu1': 0.15519337010503506, 'best_bleu2': 0.09391290091144913, 'best_bleu3': 0.05791537394797654, 'best_bleu4': 0.03430614826591653}
It doesn't reach the level of the paper.

**Comment by SuperSupermoon** [comment]
Hello, PengPeixi. Thanks for you patience. Due to code refactoring work, it has been delayed to answer. Note that the models released in this GitHub repository are pre-trained models. Therefore, to reach the performance of our paper, the pre-trained model needs to be a fine-tuning process. We will release our refactored code v.2 soon, and we will additionally reveal the performance achieved when using multiple CNN backbones soon. Please stay tuned!
